- hosts: vagrants
  roles:
    # - init
    # - mysql
    # - ruby
    # - nodejs
    # - redis
    # - elasticsearch
    - avalonsphere
    - nginx
  vars:
    __working_user: vagrant
    __app_dir: ~/eclair
