- name: Bundle install
  shell: |
    /bin/bash -lc "bundle install --path vendor/bundle"
  args:
    chdir: ~/Project/avalonsphere
  become_user: "vagrant"

- name: deploy puma
  template:
    src: "puma"
    dest: "/etc/init.d/puma"
    owner: root
    group: root
    mode: 0755

- name: start puma
  shell: |
    /bin/bash -lc "sudo service puma start"
  become_user: "vagrant"
