#!/bin/bash
 
NAME=puma # 変更なし
USER=vagrant # centOSのuserに変更
APP_NAME=avalonsphere # RailsのAppの名前に変更
APP_DIR=/home/$USER/Project/$APP_NAME # Railsをおいているディレクトリに変更
TMP_DIR=$APP_DIR/tmp
PID_DIR=$TMP_DIR/pids
SOCKET_DIR=$TMP_DIR/sockets
LOG_DIR=$TMP_DIR/logs
 
RAILS_ENV=production
 
sudo -u $USER -H sh -c "mkdir -p $PID_DIR"
sudo -u $USER -H sh -c "mkdir -p $SOCKET_DIR"
sudo -u $USER -H sh -c "mkdir -p $LOG_DIR"
 
PIDFILE=$PID_DIR/puma.pid
 
 
start() {
  cd $APP_DIR;
  sudo -u $USER /bin/bash -lc "RAILS_ENV=production bundle exec rails s &"
}
 
stop() {
  echo -n "Stopping puma"
  kill -s SIGTERM `cat $PIDFILE`
}
 
restart() {
  stop
  start
}
 
case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    restart
    ;;
  *)
    N=/etc/init.d/$NAME
    echo "Usage: $N {start|stop|restart}" >&2
    exit 1
    ;;
esac
