- name: deploy .bash_profile
  template:
    src: .bash_profile
    dest: ~/.bash_profile
    mode: 0644
  become_user: "{{ __working_user }}"

- name: mkdir .bash.d
  file:
    path: ~/.bash.d
    state: directory
    mode: 0755
  become_user: "{{ __working_user }}"

- name: stop and disable firewalld
  service:
    name: firewalld
    state: stopped
    enabled: no

- name: set LANG={{ __locale }} in /etc/locale.conf
  lineinfile:
    dest: /etc/locale.conf
    regexp: "^LANG="
    line: "LANG={{ __locale }}"
    backup: yes

- name: deploy yum.conf
  template:
    src: "yum.conf"
    dest: "/etc/yum.conf"
    owner: root
    group: root
    mode: 0644
